<a href="https://colab.research.google.com/github/Francisco-Italo/ml2023-Italo-Moraes/blob/master/Atividades/09-Ensemble-methods/09_Ensemble.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn import datasets
import pandas as pd
import numpy as np

dt = datasets.load_breast_cancer()

df = pd.DataFrame(np.c_[dt['target'], dt['data']], columns=np.r_[['target'], dt['feature_names']])

In [ ]:
df.head()

target  mean radius  mean texture  mean perimeter  mean area  \
0     0.0        17.99         10.38          122.80     1001.0   
1     0.0        20.57         17.77          132.90     1326.0   
2     0.0        19.69         21.25          130.00     1203.0   
3     0.0        11.42         20.38           77.58      386.1   
4     0.0        20.29         14.34          135.10     1297.0   

   mean smoothness  mean compactness  mean concavity  mean concave points  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   mean symmetry  ...  worst radius  worst texture  worst perimeter  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [ ]:
df.isnull().sum()

target                     0
mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

X = df.drop('target', axis=1)
y = df['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(455, 30) (455,)
(114, 30) (114,)


In [ ]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier

rf_clf = RandomForestClassifier(random_state=42)
ab_clf = AdaBoostClassifier(random_state=84)

In [ ]:
rf_clf.fit(X_train,y_train)

RandomForestClassifier(random_state=42)

In [ ]:
ab_clf.fit(X_train,y_train)

AdaBoostClassifier(random_state=84)

In [ ]:
rf_y_pred = rf_clf.predict(X_test)
ab_y_pred = ab_clf.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score,recall_score,precision_score,f1_score

print('Random Forest classifier:')
print('Accuracy Score : ' + str(accuracy_score(y_test,rf_y_pred)))
print('Precision Score : ' + str(precision_score(y_test,rf_y_pred)))
print('Recall Score : ' + str(recall_score(y_test,rf_y_pred)))
print('F1 Score : ' + str(f1_score(y_test,rf_y_pred)))

from sklearn.metrics import confusion_matrix

print('Confusion Matrix : \n' + str(confusion_matrix(y_test,rf_y_pred)))

Random Forest classifier:
Accuracy Score : 0.9824561403508771
Precision Score : 0.9876543209876543
Recall Score : 0.9876543209876543
F1 Score : 0.9876543209876543
Confusion Matrix : 
[[32  1]
 [ 1 80]]


In [ ]:
from sklearn.metrics import accuracy_score,recall_score,precision_score,f1_score

print('AdaBoosting classifier:')
print('Accuracy Score : ' + str(accuracy_score(y_test,ab_y_pred)))
print('Precision Score : ' + str(precision_score(y_test,ab_y_pred)))
print('Recall Score : ' + str(recall_score(y_test,ab_y_pred)))
print('F1 Score : ' + str(f1_score(y_test,ab_y_pred)))

from sklearn.metrics import confusion_matrix

print('Confusion Matrix : \n' + str(confusion_matrix(y_test,ab_y_pred)))

AdaBoosting classifier:
Accuracy Score : 0.9649122807017544
Precision Score : 0.963855421686747
Recall Score : 0.9876543209876543
F1 Score : 0.975609756097561
Confusion Matrix : 
[[30  3]
 [ 1 80]]


In [ ]:
from sklearn.model_selection import GridSearchCV

rf_clf = RandomForestClassifier(random_state=42)
rf_gd = {'n_estimators' : [50,100,200], 'max_depth' : [3,5,7]}

ab_clf = AdaBoostClassifier(random_state=84)
ab_gd = {'n_estimators' : [50,100,200], 'learning_rate' : [0.1,0.05,0.01,0.5]}

In [ ]:
from sklearn.model_selection import KFold

rf_gd_clf = GridSearchCV(rf_clf, param_grid=rf_gd, cv=KFold(n_splits=5))
rf_gd_clf.fit(X_train, y_train)

rf_gd_clf_pred = rf_gd_clf.predict(X_test)

print('Accuracy Score : ' + str(accuracy_score(y_test,rf_gd_clf_pred)))
print('Precision Score : ' + str(precision_score(y_test,rf_gd_clf_pred)))
print('Recall Score : ' + str(recall_score(y_test,rf_gd_clf_pred)))
print('F1 Score : ' + str(f1_score(y_test,rf_gd_clf_pred)))

confusion_matrix(y_test,rf_gd_clf_pred)

Accuracy Score : 0.956140350877193
Precision Score : 0.9634146341463414
Recall Score : 0.9753086419753086
F1 Score : 0.9693251533742332


array([[30,  3],
       [ 2, 79]])

In [ ]:
ab_gd_clf = GridSearchCV(ab_clf, param_grid=ab_gd, cv=KFold(n_splits=5)).fit(X_train, y_train)

ab_gd_clf_pred = ab_gd_clf.predict(X_test)

print('Accuracy Score : ' + str(accuracy_score(y_test,ab_gd_clf_pred)))
print('Precision Score : ' + str(precision_score(y_test,ab_gd_clf_pred)))
print('Recall Score : ' + str(recall_score(y_test,ab_gd_clf_pred)))
print('F1 Score : ' + str(f1_score(y_test,ab_gd_clf_pred)))

confusion_matrix(y_test,ab_gd_clf_pred)

Accuracy Score : 0.9736842105263158
Precision Score : 0.975609756097561
Recall Score : 0.9876543209876543
F1 Score : 0.9815950920245398


array([[31,  2],
       [ 1, 80]])

In [ ]:
rf_best = rf_gd_clf.best_estimator_
print(rf_best.feature_importances_)

ab_best = ab_gd_clf.best_estimator_
print(ab_best.feature_importances_)

[0.0432648  0.00622509 0.04182046 0.04440179 0.00362693 0.01663035
 0.10607877 0.10385288 0.00114499 0.00080531 0.02503536 0.00285906
 0.01566494 0.06369281 0.00224348 0.         0.00900985 0.0020256
 0.00309027 0.00192575 0.08122306 0.00503781 0.09588846 0.07498166
 0.00606246 0.00851403 0.06375212 0.16272767 0.00604256 0.0023717 ]
[0.    0.05  0.    0.01  0.01  0.035 0.01  0.03  0.04  0.    0.03  0.
 0.02  0.11  0.02  0.055 0.    0.035 0.03  0.055 0.02  0.03  0.05  0.045
 0.12  0.015 0.06  0.03  0.045 0.045]


In [40]:
import numpy as np

rf_sorted_indices = np.argsort(rf_best.feature_importances_)[::-1]
ab_sorted_indices = np.argsort(ab_best.feature_importances_)[::-1]

rf_top_10_indices = rf_sorted_indices[:10]
ab_top_10_indices = ab_sorted_indices[:10]

selected_features_for_rf = X_train[:, rf_top_10_indices]
selected_features_for_ab = X_train[:, ab_top_10_indices]

new_X_test_for_rf = X_test[:, rf_top_10_indices]
new_X_test_for_ab = X_test[:, ab_top_10_indices]

In [41]:
new_rf = RandomForestClassifier()
new_rf.fit(selected_features_for_rf,y_train)

new_rf_pred = new_rf.predict(new_X_test_for_rf)

In [42]:
print('Accuracy Score : ' + str(accuracy_score(y_test,new_rf_pred)))
print('Precision Score : ' + str(precision_score(y_test,new_rf_pred)))
print('Recall Score : ' + str(recall_score(y_test,new_rf_pred)))
print('F1 Score : ' + str(f1_score(y_test,new_rf_pred)))

confusion_matrix(y_test,new_rf_pred)

Accuracy Score : 0.9649122807017544
Precision Score : 0.9753086419753086
Recall Score : 0.9753086419753086
F1 Score : 0.9753086419753086


array([[31,  2],
       [ 2, 79]])

In [43]:
new_ab = AdaBoostClassifier()
new_ab.fit(selected_features_for_ab,y_train)

new_ab_pred = new_ab.predict(new_X_test_for_ab)

In [44]:
print('Accuracy Score : ' + str(accuracy_score(y_test,new_ab_pred)))
print('Precision Score : ' + str(precision_score(y_test,new_ab_pred)))
print('Recall Score : ' + str(recall_score(y_test,new_ab_pred)))
print('F1 Score : ' + str(f1_score(y_test,new_ab_pred)))

confusion_matrix(y_test,new_ab_pred)

Accuracy Score : 0.9649122807017544
Precision Score : 0.9529411764705882
Recall Score : 1.0
F1 Score : 0.9759036144578312


array([[29,  4],
       [ 0, 81]])