<a href="https://colab.research.google.com/github/Francisco-Italo/ml2023-Italo-Moraes/blob/master/Atividades/01-Pre-processamento_Limpeza_Analise_de_Dados/02_Tipos_e_Convers%C3%A3o_de_tipos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2 - Tipos e Conversão de tipos
O Numpy suporta uma variedade de tipos muito maior do que o Python.

Existem 5 tipos básicos numéricos
- Booleans (bool)
- Integers (int)
- Unsigned Intergers (uint)
- Floating Points (float)
- Complex

Complementarmente, a célula abaixo mostra um quadro comparativos com uma maior quantidade de tipos do Numpy.

![datatypes.png](attachment:datatypes.png)

In [ ]:
import numpy as np

In [ ]:
# Converte o numeral no tipo float de 32 bits
x = np.float32(1.0)
x

1.0

In [ ]:
# Converte o array em array de inteiros
y = np.int_([1,2,4])
y

array([1, 2, 4])

In [ ]:
# Declara um array com uma certa tipagem, inicializando-o em ordem crescente de 0 a um limite superior-1
z = np.arange(3, dtype=np.uint8)
z

array([0, 1, 2], dtype=uint8)

In [ ]:
# Inicializa o array com valores definidos pelo usuário com tipagem definida pelo usuário
np.array([1, 2, 3], dtype='f')

array([1., 2., 3.], dtype=float32)

## Convertendo tipos de arrays

Para convertermos arrays Numpy, basta utilizarmos o método astype().

In [ ]:
# Converte o array para float
z.astype(float)

array([0., 1., 2.])

In [ ]:
# Converte o array para inteiro
np.int8(z)

array([0, 1, 2], dtype=int8)

Para verificarmos o tipo de um array Numpy, basta verificarmos o seu atributo dtype.

In [ ]:
# Verifica o tipo do array
z.dtype

dtype('uint8')